name: flipper
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.4.12

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #  url_launcher: ^5.0.3 #stick with this version please
  flutter_svg: ^0.15.0
  #for sending emails, sync etc...
  cron: ^0.2.2
  auto_route: ^0.2.1
  # Firebase dependencies
  firebase_core: ^0.4.0
  #  flutter_webview_plugin: ^0.3.10 causing the error.
  firebase_messaging: ^5.1.3
  firebase_crashlytics: ^0.1.0+2
  http: ^0.12.0+2
  #  moor_flutter: ^2.0.0
  moor: # use the latest version
    null
  moor_ffi: null
  path_provider: null #update this to work with androix x
  path: null
  json_annotation: ^3.0.0
  cached_network_image: 1.1.3
  geolocator: ^5.2.0
  permission_handler: ^4.0.0
  flutter_circular_chart: ^0.1.0
  fluttertoast: ^3.1.3
  #  pusher_websocket_flutter: ^0.1.1
  #   Redux dependencies
  redux: ^3.0.0
  #fluttercouch:
  camera: ^0.5.7+3
  flutter_redux: ^0.5.0
  flutter_masked_text: null
  built_value: ^6.6.0
  image_picker: ^0.6.0+15
  transparent_image: ^1.0.0
  firebase_analytics: ^5.0.2
  built_collection: ^4.2.2
  # We fixed a bug in the plugin
  #  media_picker_builder:
  #    git:
  #      url: git://github.com/janoodleFTW/media_picker_builder.git
  #      ref: master
  #  flutter_native_image:
  #    git:
  #      url: https://github.com/btastic/flutter_native_image.git
  #      ref: fix/ios_compression
  #  pinch_zoom_image: ^0.2.5
  # TODO: the flutter_platform_widgets: 0.20.3-beta.1 is the only version mathing beta channel please do not change
  flutter_platform_widgets: 0.20.3-beta.1
  flutter_linkify: ^2.1.0
  #  built_collection: ^4.2.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.5.2
  auto_route_generator: null
  built_value_generator: ^6.6.0
  moor_generator: null
  json_serializable: ^3.0.0
  test: ^1.6.1
  mockito: ^4.1.0

  flutter_launcher_icons: "^0.7.2"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_foreground: "assets/icon/icon.png"
  adaptive_icon_background: "#000000"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/placeholder/user_image_placeholder.png
    - assets/graphics/avatar_no_picture.png
    - assets/graphics/analytics.svg
    - assets/graphics/credit-card.svg
    - assets/graphics/navigation.svg
    - assets/graphics/grid.svg
    - assets/graphics/menu_icon.png
    - assets/graphics/refresh.svg
    - assets/graphics/settings.svg
    - assets/graphics/logo.png
    - assets/graphics/chevron-left.svg
    - assets/graphics/chevron-right.svg
    - assets/graphics/drawer/events.png
    - assets/graphics/input/icon_add_content.png
    - assets/graphics/updates_indicator.png
    - assets/graphics/updates_indicator_white.png
    - assets/graphics/drawer/create_topic.png
    - assets/graphics/drawer/account.png
    - assets/graphics/drawer/settings.png
    - assets/graphics/arrow-up-right.svg

  fonts:
    - family: Heebo-Black
      fonts:
        - asset: fonts/Heebo-Black.ttf
    - family: Heebo-Thin
      fonts:
        - asset: fonts/Heebo-Thin.ttf
    - family: Heboo-Regular
      fonts:
        - asset: fonts/Heebo-Regular.ttf
flutter_intl:
  enabled: true

#  flutter packages pub run build_runner watch --delete-conflicting-outputs
#  rw.flipper
# flutter build appbundle  --build-number 1.4.12
