name: flipper_login
description: 'A login package for flipper app'
version: 0.0.2

homepage: 'https://yegobox.com'

environment:
  sdk: ">=2.9.2 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"


dependencies:
  flutter:
    sdk: flutter
  firebase_core: "^0.5.0"
  firebase_auth: "^0.18.0+1"
  flipper:
    path: ../../

  stacked: ^1.7.1
  stacked_hooks: 0.1.1+3
  
  stacked_services: 
  # get it
  get_it: 
  # provider
  provider: ^4.1.3
  country_code_picker: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  built_value_generator: ^7.0.9
  build_runner: 
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:


  assets:
    - packages/flipper_login/assets/cell.png
    - packages/flipper_login/assets/mobile.png

# flutter packages pub run build_runner watch --delete-conflicting-outputs  --enable-experiment=non-nullable