name: App PlayStore Release

on:
  push:
    branches: [ mobile, develop ]

jobs:      
  version:
    name: Create version number
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Fetch all history for all tags and branches
      run: |
        git config remote.origin.url https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}
        git fetch --prune --depth=10
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.5
      with:
          versionSpec: '5.5.x'
    - name: Use GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.5
    - name: Create version.txt with nuGetVersion
      run: echo ${{ steps.gitversion.outputs.nuGetVersion  }} > version.txt
    - name: Upload version.txt
      uses: actions/upload-artifact@v2
      with:
        name: gitversion
        path: version.txt

  build:
    name: Build APK and Create release
    needs: [ version ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Decode google-services.json
      env:
        FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
      run: echo $FIREBASE_SECRET > flipper/android/app/google-services.json
    - name: Get version.txt
      uses: actions/download-artifact@v2
      with:
        name: gitversion
    - name: Create new file without newline char from version.txt
      run: tr -d '\n' < version.txt > version1.txt
    - name: Read version
      id: version
      uses: juliangruber/read-file-action@v1
      with:
        path: version1.txt
    - name: Update version in YAML
      run: sed -i 's/99.99.99+99/${{ steps.version.outputs.content }}+${{ github.run_number }}/g' pubspec.yaml
    - name: Update KeyStore password in gradle properties
      run: sed -i 's/#{KEYSTORE_PASS}#/${{ secrets.KEYSTORE_PASS }}/g' android/key.properties
    - name: Update KeyStore key password in gradle properties
      run: sed -i 's/#{KEYSTORE_KEY_PASS}#/${{ secrets.KEYSTORE_KEY_PASS }}/g' android/key.properties
    - name: Update env URL
      run: sed -i 's/#{URL}#/${{ secrets.URL }}/g'  .env
    - name: Update env PASS
      run: sed -i 's/#{PASS}#/${{ secrets.PASS }}/g' .env
    - name: Update env GMPASS
      run: sed -i 's/#{GMPASS}#/${{ secrets.GMPASS }}/g' .env
    # - name: Update google-services.json
    #   run: sed -i 's/#{GMPASS}#/${{ secrets.GMPASS }}/g' .env  
    # - name: JSON
    #   run: sed -i 's/#{FIREBASE_URL}#/${{ secrets.FIREBASE_URL }}/g' google-services.json
    # - name: JSON
    #   run: sed -i 's/#{STORAGE_BUCKET}#/${{ secrets.STORAGE_BUCKET }}/g' google-services.json
    # - name: JSON
    #   run: sed -i 's/#{OAHTH_CLIENT_ID}#/${{ secrets.OAHTH_CLIENT_ID }}/g' google-services.json
    # - name: JSON
    #   run: sed -i 's/#{CLIENT_ID_FLIPPER}#/${{ secrets.CLIENT_ID_FLIPPER }}/g' google-services.json
    # - name: JSON
    #   run: sed -i 's/#{CERTIFICATE_HASH_FLIPPER}#/${{ secrets.CERTIFICATE_HASH_FLIPPER }}/g' google-services.json

    - uses: actions/setup-java@v1
      with:
        java-version: '8.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.22.3'
        channel: 'stable'
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk --release --split-per-abi --no-tree-shake-icons
    - run: flutter build appbundle --no-tree-shake-icons
    - name: Create a Release in GitHub
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/release/*.apk,build/app/outputs/bundle/release/app-release.aab"
        token: ${{ secrets.GH_TOKEN }}
        tag: ${{ steps.version.outputs.content }}
        commit: ${{ github.sha }}
    - name: Upload app bundle
      uses: actions/upload-artifact@v2
      with:
        name: appbundle
        path: build/app/outputs/bundle/release/app-release.aab      
  release:
    name: Release app to internal track
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Get appbundle from artifacts
      uses: actions/download-artifact@v2
      with:
        name: appbundle
    - name: Release app to internal track
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.PLAYSTORE_ACCOUNT_KEY }}
        packageName: rw.flipper
        releaseFile: app-release.aab
        track: internal
        whatsNewDirectory: distribution/whatsnew            
 
#  another release and here so!@