name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        package_manager: [npm]
        #  macos-latest, ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 12
      # - name: "print env"
      #   run:
      #     echo $ENV_PROD
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      #   with:
      #     sudo: false
      - name:
        run: echo $ENV_PROD >> .env
      - name: Update env
        run: |
          yarn add  ts-node
          yarn run config -- --environment=prod
          yarn run config -- --environment=dev
      - name: Yarn clean
        # Clean Yarn package
        run: |
         yarn cache clean

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
